/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ElOsitoAzul (https://sketchfab.com/ElOsitoAzul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hand-with-a-bouquet-of-flowers-mano-low-poly-f38e4171756c4b48acac3bd339ead876
Title: Hand with a bouquet of flowers / mano low poly
*/

import * as THREE from "three";
import { FunctionComponent, useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { Group, Vector3 } from "three";

const path = "/flowers/scene.gltf";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_9: THREE.SkinnedMesh;
    Object_33: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_49: THREE.Mesh;
    GLTF_created_0_rootJoint: THREE.Bone;
  };
  materials: {
    JACKET: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshPhysicalMaterial;
    ["Material.001"]: THREE.MeshPhysicalMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
};

export const Bouquet: FunctionComponent<{
  position: [number, number, number];
  rotation?: [number, number, number];
  showNumFlowers: number;
  showAnimation: boolean;
}> = ({ position, rotation, showNumFlowers, showAnimation }) => {
  const { nodes, materials } = useGLTF(path) as GLTFResult;

  const target = new Vector3(-1.25, 0.4, 1.25);
  const group = useRef<Group>(null);

  useFrame((_, delta) => {
    if (!group.current || !showAnimation) return;

    group.current.position.lerp(target, delta * 3);
  });

  useEffect(() => {
    if (showNumFlowers !== 0) return;

    group.current?.position.fromArray(position);
  }, [showNumFlowers]);

  return (
    <group position={position} rotation={rotation} ref={group}>
      <group
        position={[-0.75, -1.5, 1.5]}
        rotation={[0, Math.PI, 0]}
        dispose={null}
      >
        {/* HAND */}
        <group visible={true}>
          <group position={[0, 1.546, 1.396]} rotation={[-Math.PI / 2, 0, 0]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_9.geometry}
              material={materials.Material}
              skeleton={nodes.Object_9.skeleton}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.JACKET}
            position={[-0.761, 1.512, 0.956]}
            rotation={[-1.528, 1.047, 0]}
            scale={[1.337, 1.523, 1.337]}
          />
        </group>

        {/* FLOWER 1 */}
        <group visible={showNumFlowers >= 1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials["Material.001"]}
            position={[-0.716, 2.578, -0.186]}
            rotation={[-1.876, -1.165, -2.189]}
            scale={0.048}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials["Material.002"]}
            position={[-0.665, 2.544, -0.158]}
            rotation={[-1.973, -1.134, -2.278]}
            scale={[0.067, 0.089, 0.067]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials["Material.003"]}
            position={[-0.631, 2.297, -0.303]}
            scale={0.038}
          />
        </group>

        {/* FLOWER 2 */}
        <group visible={showNumFlowers >= 2}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials["Material.001"]}
            position={[-0.44, 2.705, -0.414]}
            rotation={[-1.461, -1.058, -1.292]}
            scale={0.048}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials["Material.002"]}
            position={[-0.384, 2.674, -0.393]}
            rotation={[-1.561, -1.069, -1.38]}
            scale={[0.067, 0.09, 0.067]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials["Material.003"]}
            position={[-0.631, 2.314, -0.423]}
            scale={0.038}
          />
        </group>

        {/* FLOWER 3 */}
        <group visible={showNumFlowers >= 3}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials["Material.001"]}
            position={[-0.774, 2.553, -0.664]}
            rotation={[-0.598, -0.802, -0.309]}
            scale={0.043}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials["Material.002"]}
            position={[-0.721, 2.531, -0.678]}
            rotation={[-0.621, -0.85, -0.326]}
            scale={[0.059, 0.079, 0.059]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials["Material.003"]}
            position={[-0.613, 1.721, -0.481]}
            scale={0.038}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload(path);
